---
# Add the elasticsearch user before installing from packages.
- name: Ensure optional elasticsearch group is created with the correct id.
  become: true
  # Restart if these change
  notify: restart elasticsearch
  group:
    state: present
    name: '{{ es_group }}'
    system: true
    gid: '{{ es_group_id }}'
- name: Ensure optional elasticsearch user is created with the correct id.
  become: true
  # Restart if these change
  notify: restart elasticsearch
  user:
    state: present
    name: '{{ es_user }}'
    comment: elasticsearch system user
    system: true
    createhome: false
    uid: '{{ es_user_id }}'
    group: '{{ es_group }}'
