---
- name: Include specific Elasticsearch
  include_tasks: elasticsearch-Debian.yml
  when: ansible_facts["os_family"] == 'Debian'
- name: Include specific Elasticsearch
  include_tasks: elasticsearch-RedHat.yml
  when: ansible_facts["os_family"] == 'RedHat'
